[package]
name = "Rust-Controller"
version = "0.1.0"
authors = ["tsuika98 <tsuika98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
